### PR TITLE
Add 'terraform fmt' check and fix files formatting in assets

### LINKED ISSUE #115: Run 'terraform fmt' as part of CI
So all Terraform files are consistently formatted.

Just calling `terraform fmt -recursive assets/` should be enough, though we need to make sure Terraform binary is available in CI image.

When we do it, we could also remove `e2e` tag from Terraform executor test actually.

### PR DESCRIPTION
**Pull request by invidian**
Closes #115

### CODE REVIEW

**Comment by knrt10** [comment]
Can you please check the CI errors @invidian ?

**Comment by knrt10** [comment]
@invidian for second commit 

> Found using Terraform 0.14.4

But required version that we suggest is `>= 0.13, < 0.14`. should we lint with v0.14+ ?

**Comment by invidian** [comment]
>But required version that we suggest is >= 0.13, < 0.14. should we lint with v0.14+ ?

We should actually upgrade to Terraform 0.14 everywhere. See #1262.

**Comment by knrt10** [comment]
Cool, then this should be merged after we update to terraform v0.14+

**Comment by invidian** [comment]
>Cool, then this should be merged after we update to terraform v0.14+

No. I think it's fine to merge it right now.

**Review by knrt10 — APPROVED** [review]
+1

**Pull request merged**
