### PR TITLE
fix: update broken links

### PR DESCRIPTION
**Pull request by ipochi**
This commit fixes the broken relative links in the repository.

Signed-off-by: Imran Pochi <imran@kinvolk.io>

### CODE REVIEW

**Comment by ipochi** [comment]
> LGTM. Do we have some tool to automatically catch this kind of things?

I used this https://github.com/tcort/markdown-link-check

Also the links to gpg keys in KEYS.md are broken. Could @invidian @iaguis please verify the link and check if the links are fine.

**Comment by invidian** [comment]
@ipochi can you please create an issue so we add something like this to the CI?

**Comment by ipochi** [comment]
@invidian created #571

**Comment by invidian** [comment]
Thanks :)

**Pull request merged**
