### PR TITLE
Document initial release process

### PR DESCRIPTION
**Pull request by invidian**
## NOTE: While testing goreleaser, please use separated repository!

Initial draft of release process documentation.

Refs #54.

### CODE REVIEW

**Comment by iaguis** [comment]
Closing in favor of #147

**Comment by surajssd** [comment]
mind deleting the branch @invidian ?

**Comment by invidian** [comment]
Done. I blame @iaguis :smile:

**Comment by iaguis** [comment]
My muscle memory only works for merged PRs, not closed ones :(

**Pull request closed without merging**
