### PR TITLE
calico: Use the upstream quay hosted images

### PR DESCRIPTION
**Pull request by surajssd**
Fixes https://github.com/kinvolk/lokomotive/issues/1458

### CODE REVIEW

**Comment by surajssd** [comment]
```console
# docker ps -a
CONTAINER ID   IMAGE         COMMAND                   CREATED          STATUS                      PORTS  NAMES
03836c5fe07a   21fdaa2fccee  "/opt/cni/bin/calico…"    4 seconds ago    Exited (1) 3 seconds ago           k8s_upgrade-ipam_calico-node-26tt8_kube-system_8ab4eeb1-07de-4b41-a295-f42b666e79fa_17
```

```console
# docker logs 03836c5fe07a
standard_init_linux.go:206: exec user process caused: exec format error
```

Right now the above pod fails which is created from `quay.io/calico/cni:v3.18.1` image. This image is not yet ARM supported it seems.

**Comment by iaguis** [comment]
Let's report this to upstream. Until this happens this is blocked.

**Comment by surajssd** [comment]
Reported upstream: https://github.com/projectcalico/calico/issues/4692

**Comment by ipochi** [comment]
update from upstream
https://github.com/projectcalico/calico/issues/4692#issuecomment-901193583

**Comment by surajssd** [comment]
I guess that will need lot of changes on how we decide which image to pull. So let us stick to our current way of reuploading images.

**Pull request closed without merging**
