### PR TITLE
Remove provider aliases from go templates

### PR DESCRIPTION
**Pull request by knrt10**
Signed-off-by: knrt10 <kautilya@kinvolk.io>

### CODE REVIEW

**Comment by iaguis** [comment]
Has this been tested successfully with upgrades?

I'd welcome a bit more context in the commit message.

**Comment by invidian** [comment]
From my testing, this required running `sed` on `terraform.tfstate` file, which is not great.

**Comment by knrt10** [comment]
@iaguis @invidian I tested for up-gradation and it worked fine. First I deployed cluster on packet using `master` branch and then applied the patch in this PR and reapplied the cluster and everything worked fine. You can check the final pic shown below. Also I have updated the commit message for more information

### Initial

Initial

### Final

Testing

**Comment by invidian** [comment]
I'll test again now.

**Pull request merged**
