### PR TITLE
Enable e2e tests for Prometheus Operator on Packet FLUO pipeline

### LINKED ISSUE #397: Test rook-ceph component in e2e tests
Right now we test only rook which essentially does not deploy anything important(it deploys operator which is kicked into action once we create a CR called `CephCluster` using `rook-ceph` component).

So this deploy rook-ceph via CI config. But before doing this we need to make sure there are machines available to run rook-ceph on. This component needs raw disk which it uses for its own purpose, they can't conflict with OpenEBS. So we need to add extra machines, label them so that rook is deployed there and now use some other component to test if it can create PVC from rook.

### PR DESCRIPTION
**Pull request by invidian**
It should've been added in #1084.

Closes #397

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

### CODE REVIEW

**Comment by invidian** [comment]
ping @surajssd

**Comment by surajssd** [comment]
@invidian what is the motivation of testing the component again in this pipeline?

**Comment by invidian** [comment]
>@invidian what is the motivation of testing the component again in this pipeline?

To ensure that prometheus operator workloads converges with alternative storage, which may not be covered by Helm's `--wait` (e.g. if readiness probes are disabled/removed). It's a cheap sanity check.

**Comment by surajssd** [comment]
Please rebase :-)

**Comment by invidian** [comment]
@surajssd done.

**Review by surajssd — DISMISSED** [review]
LGTM :+1:

**Comment by invidian** [comment]
Had to rebase to include pipeline fixes.

**Review by surajssd — APPROVED** [review]

**Pull request merged**
