### PR TITLE
Use logrus to log info to the user

### PR DESCRIPTION
**Pull request by BrainBlasted**
logrus provides more information than `fmt` functions do,
and this helps standardize the way we present information
from lokomotive.

Related to https://github.com/kinvolk/lokomotive/issues/320

### CODE REVIEW

**Comment by johananl** [comment]
Thanks @BrainBlasted! I like the initiative and am happy you've picked this up :+1: 

While I do think it makes sense to "unify" the output we show to the user, I'm wondering about the following:

Should we separate the `lokoctl` output to two categories - **user output** and **logs**? By "user output" I mean text which constructs the UI, in this case a text-based UI (as opposed to a GUI). By "logs" I mean messages which are more diagnostic in nature and aren't a part of the UI.

To make this distinction clearer, imagine `lokoctl` was a *graphical* UI rather than a text-based UI. Which text would you build into the GUI and which text would you, say, write to a log file?

To make this even more concrete, in the current state the following looks weird to me:

```
INFO[0694] 
Your configurations are stored in ./assets   args="[]" command="lokoctl cluster apply"

Now checking health and readiness of the cluster nodes ...

Node                             Ready    Reason          Message                            
                                                                                             
johannes-test-pool-1-worker-1    True     KubeletReady    kubelet is posting ready status    
johannes-test-controller-0       True     KubeletReady    kubelet is posting ready status    
johannes-test-pool-1-worker-0    True     KubeletReady    kubelet is posting ready status    

Success - cluster is healthy and nodes are ready!
```

Having `INFO[xxxx]` on lines which are clearly user output is weird IMO. Same goes for having things like `args="[]" command="lokoctl cluster apply"` mixed with the user output. I'm wondering if we even need these pieces of information *at all* (because if we hadn't, the question above would be less relevant).

Happy to hear any thoughts on this.

**Comment by BrainBlasted** [comment]
> Having INFO[xxxx] on lines which are clearly user output is weird IMO.

You're right. Though some lines are a bit confusing as to whether they're strictly user output, or would be useful for diagnostics. Should all lines visible to the user running `lokoctl cluster apply`, for example, be considered user output?

**Comment by invidian** [comment]
>Happy to hear any thoughts on this.

I think we need to put a bit more though in how do we handle the user output. In my opinion using a logger for user output everywhere is a good thing, **however** we should do more in terms of formatting the output. I have a following idea: when logging on INFO level, we should skip `INFO[xxxx]` and other standard pieces and just print a text, like we would do with `fmt.Println`. And for DEBUG logs, it should be fine to mix `DEBUG[xxxx]` output with regular lines printed on INFO level. Or we could format them the same way as DEBUG logs then, for consistency, as while debugging, the UX is not so important.

Another thing is, that I have some doubts regarding the DEBUG logs, as it is difficult to predict in which places to put them and with what information to make them useful, which may lead to some abuse of those in the code. Maybe we could even skip them entirely? Logging seems more useful to me for event-driven applications like web-server and not necessarily for the CLI tools. 

Last though for the further work is, that I think we should treat logging as a dependency of our objects and code, so it is easier to control the behavior of logs (to be able to suppress them or redirect to file programatically, if needed).

**Comment by johananl** [comment]
> > Having INFO[xxxx] on lines which are clearly user output is weird IMO.
> 
> You're right. Though some lines are a bit confusing as to whether they're strictly user output, or would be useful for diagnostics. Should all lines visible to the user running `lokoctl cluster apply`, for example, be considered user output?

I don't have a concrete concept in mind regarding what should be user-facing output and what shouldn't. I mainly wanted to raise the question because I sensed it was glossed over.

**Comment by johananl** [comment]
>I think we need to put a bit more though in how do we handle the user output. In my opinion using a logger for user output everywhere is a good thing, however we should do more in terms of formatting the output. I have a following idea: when logging on INFO level, we should skip INFO[xxxx] and other standard pieces and just print a text, like we would do with fmt.Println. And for DEBUG logs, it should be fine to mix DEBUG[xxxx] output with regular lines printed on INFO level. Or we could format them the same way as DEBUG logs then, for consistency, as while debugging, the UX is not so important.

I agree.

>Another thing is, that I have some doubts regarding the DEBUG logs, as it is difficult to predict in which places to put them and with what information to make them useful, which may lead to some abuse of those in the code.

The beauty about logging is that we *don't* need to predict where we may want to log. It's the same as tracing or metrics: all we have to do is initialize logging centrally and use a tried-and-true method for making the logger available in arbitrary parts of the code. I'm sure there are Go best practices for that, and likely a bunch of community practices as well. Happy to do a bit of research about this if you guys need my help there.

>Maybe we could even skip them entirely? Logging seems more useful to me for event-driven applications like web-server and not necessarily for the CLI tools.

I disagree. I think complex CLI tools definitely need logging. Take Terraform for example. How many times were you able to solve a problem by running the tool with `TF_LOG=debug`? `lokoctl` is at least as complex as Terraform because it uses Terraform...

**Comment by invidian** [comment]
>The beauty about logging is that we don't need to predict where we may want to log. It's the same as tracing or metrics: all we have to do is initialize logging centrally and use a tried-and-true method for making the logger available in arbitrary parts of the code.

I agree that it's important to keep it around so it's available, but as I said, we need to be careful what we log to avoid cluttering the output. 

>I'm sure there are Go best practices for that, and likely a bunch of community practices as well. Happy to do a bit of research about this if you guys need my help there.

Still on my TODO list, if someone has some proven expertise, I'm happy to learn :smile: 

>I disagree. I think complex CLI tools definitely need logging. Take Terraform for example. How many times were you able to solve a problem by running the tool with TF_LOG=debug? lokoctl is at least as complex as Terraform because it uses Terraform...

Well, `TF_LOG=debug` is only helpful in particular cases, mainly debugging 3rd party providers I'd say, but yeah, as we discussed above, keeping it a round definitely make sense. Thanks @johananl.

**Comment by invidian** [comment]
Hm, how should we proceed with this PR? @BrainBlasted would you like to continue working on it, taking our feedback into account? Or should we make a summary of findings in the issue and close it, so we can make another attempt another time?

**Comment by surajssd** [comment]
Any updates on this PR?

**Comment by invidian** [comment]
I'll close this PR and we can come back to it later.

**Pull request closed without merging**
