### PR TITLE
Makefile: Run unit tests only for `pkg` dir

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by invidian** [comment]
Why is this needed? What if we have e.g. `internal` directory later, as a non-exported packages?

**Comment by iaguis** [comment]
Yes, I'm missing the reasoning for this change.

**Comment by surajssd** [comment]
> Why is this needed? What if we have e.g. `internal` directory later, as a non-exported packages?

Why do we have to base our current decisions on some hypothetical future? Right now running providing unnecessary directories is slowing down the test run.

---

With just `pkg/...`

```bash
...
=== RUN   TestWriteFileTruncate
--- PASS: TestWriteFileTruncate (0.00s)
PASS
coverage: 16.7% of statements
ok      github.com/kinvolk/lokomotive/pkg/util/walkers  0.010s  coverage: 16.7% of statements
?       github.com/kinvolk/lokomotive/pkg/version       [no test files]

real    0m40.600s
user    3m52.291s
sys     0m31.405s
```

With entire `/...`

```bash
...
=== RUN   TestWriteFileTruncate
--- PASS: TestWriteFileTruncate (0.00s)
PASS
coverage: 16.7% of statements
ok      github.com/kinvolk/lokomotive/pkg/util/walkers  0.050s  coverage: 16.7% of statements
?       github.com/kinvolk/lokomotive/pkg/version       [no test files]
?       github.com/kinvolk/lokomotive/test/components/util      [no test files]

real    0m39.923s
user    4m3.867s
sys     0m26.166s
```

Not big of a difference, but then I think worth an efficiency.

**Comment by iaguis** [comment]
That makes sense to me, a commit message with that reasoning would help :)

**Comment by invidian** [comment]
If the idea is to get rid of `e2e` build tag, then I would be cautious about it, as it is common to just run `go test ./...` on the project, so I think we should guard against more functional tests anyway.

BTW, what kind of tests are skipped with this change?

**Comment by surajssd** [comment]
We have unit tests only in `pkg` dir. Which is where all the code resides for components, clusters, etc. And hence making the scope of the test run to just target that. All the e2e tests are in `test` dir that need not be run with unit test target.

**Comment by surajssd** [comment]
Updated the commit message to include all the information.

**Comment by invidian** [comment]
This seems like a premature optimization to me.

**Comment by surajssd** [comment]
> This seems like a premature optimization to me.

@invidian can you elaborate on how is this "premature"?

**Comment by invidian** [comment]
The gain from it seems insagnificant to me and I see at least one argument against it, as mentioned above, so I disagree that we should include this change.

**Comment by surajssd** [comment]
> Why is this needed? What if we have e.g. `internal` directory later, as a non-exported packages?

This argument? I don't understand this argument can you give a concrete example when this can happen?

**Comment by invidian** [comment]
>This argument? I don't understand this argument can you give a concrete example when this can happen?

Yes, this. It's quite common in the Go projects to have `internal` directory for the packages, which shouldn't be exported for other projects. I think we should make better use of it in the future.

This also applies to any other subdirectory than `pkg`. If we add such with unit tests (e.g. we could add tests to `test/components/util`), they will never run, as running tests via `make` is recommended way of doing so.

**Comment by iaguis** [comment]
I'll close this for now, we can reconsider in the future.

**Pull request closed without merging**
