### PR TITLE
packet: ignore changes to plan and user_data on controller nodes

### LINKED ISSUE #803: Warn users about control plane data lost when changing controller node_type
As explained in the [warning for the 0.3.0 release][link], if the controller instance types are changed in lokomotive and you just run an `lokoctl cluster apply`, it will kill the nodes, lose all your data and create new controllers with empty etcd.

We should at least prevent a user doing a seemingly valid change, to destroy their cluster without any warning. Not sure if this is easy to do today in the code, though.

To avoid issues until we can get the code to prevent this, we maybe can document this limitation ASAP.

[link]: https://github.com/kinvolk/lokomotive/blob/master/CHANGELOG.md#packet

### LINKED ISSUE #898: Upgrade to `8a115b5` (or latest master) from `0.3.0` lokomotive is destructive
Packet terraform provider was updated from `2.7.3` to `3.0.0`. Since `2.10.0` there was a change merged that forces the recreation of node on user data change.

Change: https://github.com/packethost/terraform-provider-packet/pull/237
Issue: https://github.com/packethost/terraform-provider-packet/issues/236

Due to this upgrade in Packet TF provider, the upgrade from `v0.3.0` to latest will recreate clusters.

## Possible solutions

- Revert back to older version of Packet TF provider.
- Add a `ignore_changes` attribute: https://www.terraform.io/docs/configuration/resources.html#ignore_changes as suggested by @invidian

**This issue is blocker to the release** https://github.com/kinvolk/lokomotive/issues/891

### PR DESCRIPTION
**Pull request by invidian**
We recently updated Packet Terraform provider which triggers controller
nodes to be replaced if user_data of the device changes, which is
undesired, as we currently do not support graceful replacement of
controller nodes, so if one runs 'terraform apply' with such changes,
all controller nodes will be replaced at the same time, which will cause
etcd data loss and cluster outage.

Additionally, changing 'controller_type' parameter will cause similar
behavior.

To mitigate the risk of losing data from the cluster, this commit adds
ignore_changes lifecycle hook to controller nodes on Packet, so changes
to 'user_data' and 'plan' fields won't be triggering node replacement.

If user wants to actually apply those changes, cluster should be
recreated.

Closes #898
Closes #803

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

### CODE REVIEW

**Comment by invidian** [comment]
@surajssd this however, does not prevent worker nodes from being replaced when `user_data` changes. Should we ignore `user_data` also for worker nodes and let user delete the instances manually so then `lokoctl cluster apply` can re-create them?

**Comment by surajssd** [comment]
> Should we ignore `user_data` also for worker nodes and let user delete the instances manually so then `lokoctl cluster apply` can re-create them?

How do we handle the situation where there is stateful data? Lokoctl does not have a feature to only upgrade a specific worker pool. I say this because we could have added a pool with new configs for rook ceph let ceph synchronise the data in the new pool and nuke the old pool. I am wondering how the upgrade of such nodes will look like?

**Comment by iaguis** [comment]
I think we should ignore `user_data` for workers to maintain the previous behavior. We can later figure out a way to remove this by not modifying `user_data` unless it's necessary.

**Comment by surajssd** [comment]
We can toggle behaviour behind a variable per worker pool? Is that possible @invidian ?

**Comment by invidian** [comment]
>We can toggle behaviour behind a variable per worker pool? Is that possible @invidian ?

I don't think so :cry: We would have to move the worker pool userdata to separate module and then add `lifecycle { ignore_changes = [] }` conditionally in the root module, which I would rather avoid for now.

**Review by surajssd — APPROVED** [review]
LGTM, tested and it worked.

**Review by iaguis — APPROVED** [review]
lgtm

**Comment by invidian** [comment]
I'll merge. @rata if you have some extra comments, please comment here, I'll address them in separate PR.

**Comment by rata** [comment]
LGTM, thanks @invidian !

**Pull request merged**
