### PR TITLE
etcd - ETCD_ env var prefix for standard vars only

### LINKED ISSUE #1065: Don't use environment variable prefix ETCD_ for non standard etcd environment variables in systemd unit
As they make etcd logs the following messages:
```
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754467 I | pkg/flags: recognized and used environment variable ETCD_PEER_CLIENT_CERT_AUTH=true
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754482 I | pkg/flags: recognized and used environment variable ETCD_PEER_KEY_FILE=/etc/ssl/etcd/etcd/peer.key
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754511 I | pkg/flags: recognized and used environment variable ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/etcd/etcd/peer-ca.crt
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754529 I | pkg/flags: recognized and used environment variable ETCD_STRICT_RECONFIG_CHECK=true
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754555 I | pkg/flags: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/ssl/etcd/etcd/server-ca.crt
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754569 W | pkg/flags: unrecognized environment variable ETCD_IMAGE_TAG=v3.4.13
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754596 W | pkg/flags: unrecognized environment variable ETCD_IMAGE_URL=quay.io/coreos/etcd
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754605 W | pkg/flags: unrecognized environment variable ETCD_SSL_DIR=/etc/ssl/etcd
Oct 12 13:14:07 tink-controller-0 96c53009bb40[846]: 2020-10-12 13:14:07.754615 W | pkg/flags: unrecognized environment variable ETCD_USER=etcd
```

### PR DESCRIPTION
**Pull request by kskewes**
Closes #1065 

etcd parses all environment variables beginning with `ETCD_` by default and warns if any variables matching this pattern exist that it doesn't explicitly support.

This PR drops the `ETCD_` prefix for custom environment variables and group these vars together at top of file.

There doesn't appear to be any variable collisions in the files with the new names. For example, `kubelet` env vars are prefixed `KUBELET_`.

# How to use

- build PR
- provision lokomotive on any supported platform

# Testing done

Provision Lokomotive using bare-metal guide on libvirt host.
Wait for etcd to start up and check logs for warnings, finding none.

Log output:
```

Jan 10 03:27:03 k8s-m-amd64-00.k8s.example.com sh[1070]: Status: Downloaded newer image for quay.io/coreos/etcd:v3.4.13
Jan 10 03:27:11 k8s-m-amd64-00.k8s.example.com sh[1070]: 76d58d741b75d030ee644cf2042782d29f40b189a2f36ebd4777743284701ebc
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com systemd[1]: Started etcd (System Application Container).
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538058 I | pkg/flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=https://k8s-m-amd64-00.k8s.example.com:2379
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538112 I | pkg/flags: recognized and used environment variable ETCD_CERT_FILE=/etc/ssl/etcd/etcd/server.crt
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538122 I | pkg/flags: recognized and used environment variable ETCD_CLIENT_CERT_AUTH=true
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538130 I | pkg/flags: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538150 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=https://k8s-m-amd64-00.k8s.example.com:2380
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538156 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=k8s-m-amd64-00=https://k8s-m-amd64-00.k8s.example.com:2380,k8s-m-amd64-01=https://k8s-m-amd64-01.k8s.example.com:2380,k8s-m-amd64-02=https://k8s-m-amd64-02.k8s.example.com:2380
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538163 I | pkg/flags: recognized and used environment variable ETCD_KEY_FILE=/etc/ssl/etcd/etcd/server.key
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538169 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538176 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_METRICS_URLS=http://0.0.0.0:2381
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538182 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538192 I | pkg/flags: recognized and used environment variable ETCD_NAME=k8s-m-amd64-00
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538198 I | pkg/flags: recognized and used environment variable ETCD_PEER_CERT_FILE=/etc/ssl/etcd/etcd/peer.crt
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538231 I | pkg/flags: recognized and used environment variable ETCD_PEER_CLIENT_CERT_AUTH=true
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538240 I | pkg/flags: recognized and used environment variable ETCD_PEER_KEY_FILE=/etc/ssl/etcd/etcd/peer.key
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538245 I | pkg/flags: recognized and used environment variable ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/etcd/etcd/peer-ca.crt
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538254 I | pkg/flags: recognized and used environment variable ETCD_STRICT_RECONFIG_CHECK=true
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538277 I | pkg/flags: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/ssl/etcd/etcd/server-ca.crt
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538316 I | etcdmain: etcd Version: 3.4.13
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538333 I | etcdmain: Git SHA: ae9734ed2
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538337 I | etcdmain: Go Version: go1.12.17
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538341 I | etcdmain: Go OS/Arch: linux/amd64
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: 2021-01-10 03:27:16.538344 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
Jan 10 03:27:17 k8s-m-amd64-00.k8s.example.com docker[1227]: [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
```

### CODE REVIEW

**Comment by surajssd** [comment]
Something is wrong with CI similar to #1309

**Comment by kskewes** [comment]
Rebased on master after etcd version update PR.

There are a couple of different template/configuration patterns across the various cloud providers, probably related to #1235

**Review by invidian — COMMENTED** [review]
Looks good from manual check. I'm running CI checks in #1324 to verify things are working everywhere.

I also think it would be nice to have some sort of tests for it, checking `journalctl -u etcd | grep 'unrecognized environment variable'`. They shouldn't be too hard to implement, we already have few tests which read infromation from the host using DaemonSet.

**Comment by invidian** [comment]
CI in #1324 is passing BTW :)

**Comment by kskewes** [comment]
Sure, will add a test. :)

**Comment by kskewes** [comment]
Added a test and tried it on a bare-metal cluster deployed with `lokoctl` built from master and then again from this branch

```
# master branch - test fails (exits 1) as unrecognized vars exist
core@k8s-m-amd64-00 ~ $ test 0 -eq $(journalctl -u etcd.service -q -g 'unrecognized environment variable' | wc -l)
core@k8s-m-amd64-00 ~ $ echo $?
1

# this branch - test succeeds (exits 0) as no unrecognized vars exist
core@k8s-m-amd64-00 ~ $ test 0 -eq $(journalctl -u etcd.service -q -g 'unrecognized environment variable' | wc -l)
core@k8s-m-amd64-00 ~ $ echo $?
0

# this branch - validate what happens with matching string, eg: recognized vars
core@k8s-m-amd64-00 ~ $ test 0 -eq $(journalctl -u etcd.service -q -g 'recognized and used environment variable' | wc -l)
core@k8s-m-amd64-00 ~ $ echo $?
1
```

**Review by invidian — APPROVED** [review]
LGTM, awesome work @kskewes thanks a lot for that! I'm running tests in #1324 now and when they pass, we can merge.

**Comment by invidian** [comment]
Ci on #1324 is :heavy_check_mark:

**Pull request merged**
