### PR TITLE
docs: Rename upgrade docs to update docs

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Review by knrt10 — APPROVED** [review]

**Review by invidian — COMMENTED** [review]
Why is this needed? Please add some explanation to commit message why we should prefer `update` over `upgrade`, as it is not obvious (to me at least).

**Comment by surajssd** [comment]
@invidian the only context I have is https://github.com/kinvolk/lokomotive/pull/1292#pullrequestreview-559958725, but @knrt10 can add more I think. So I was trying to make the change homogenous.

**Comment by knrt10** [comment]
More context https://github.com/kinvolk/lokomotive/pull/1118#discussion_r510837583

**Review by invidian — APPROVED** [review]
Hmm, I'm not entirely sure this is what @johananl had in mind. I mean, if it should apply to all use of "upgrade" word.

However, after looking at https://www.quora.com/What-is-the-difference-between-upgrade-and-update for example, it seems to me that indeed use of word `update` is more accurate than `upgrade` in most cases, as I cannot find a good example of "grades" in our case. I suppose one could **upgrade** from **Flatcar** to **Flatcar LTS**, as it is a different grade of a product, but for Lokomotive, there is no equivalent. It's the same for mentioned Terraform.

Perhaps we could include that in our style guide to avoid further confusion.

**Pull request merged**
