### PR TITLE
Remove Deprecated CoreOS from Bare Metal terraform

### PR DESCRIPTION
**Pull request by kskewes**
- remove CoreOS from terraform, closing #324
- unify `os_channel` on bare-metal, closing #445

After starting found this [commit](https://github.com/kinvolk/lokomotive/commit/79e4acc301b698c31dfe82704235cca881a21c50) which is almost the same.

```
$ go test
PASS
ok      github.com/kinvolk/lokomotive/pkg/platform/baremetal    0.020s
```

### CODE REVIEW

**Comment by kskewes** [comment]
Sorry pushed a bit quick. Have built new `lokoctl` exec and currently validating behaviour with bare-metal (libvirtd) cluster, config via matchbox.

**Comment by kskewes** [comment]
Have run in to #1191. Otherwise seems fine. Investigating.

**Review by invidian — APPROVED** [review]
LGTM. I'm testing it manually on separate CI pipeline.

**Comment by invidian** [comment]
CI is passing and I no longer see syntax deprecation warnings :tada: Thanks a lot for your contribution @kskewes!

**Pull request merged**
