### PR TITLE
velero: add AWS plugin support for Velero.

### PR DESCRIPTION
**Pull request by ipochi**
This commit adds support for Velero AWS plugin.
Signed-off-by: Imran Pochi <imran@kinvolk.io>

### CODE REVIEW

**Comment by ipochi** [comment]
This can be closed in favor of #1285

**Comment by invidian** [comment]
@ipochi this is your PR so please go ahead and close it :smile:

**Comment by ipochi** [comment]
Will do.

**Comment by invidian** [comment]
Can branch be cleaned up too?

**Pull request closed without merging**
