### PR TITLE
Update aws-ebs-csi-driver to v0.8.1

### LINKED ISSUE #1320: Update aws-ebs-csi-driver to v0.8.1
To address https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/548.

### PR DESCRIPTION
**Pull request by invidian**
Closes #1320

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

Tested manually and PVCs are bound.

### CODE REVIEW

**Comment by knrt10** [comment]
I'm really confused by their versioning. Their release says [0.8.2](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/tag/helm-chart-aws-ebs-csi-driver-0.8.2) and in charts.yaml.it says 0.8.1 🤦🏽

**Comment by invidian** [comment]
@knrt10 the driver version is [v0.8.1](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/tag/v0.8.1). Chart version is `v0.8.2`.

**Comment by invidian** [comment]
Rebased on master to poke the CI (it didn't run?).

**Comment by surajssd** [comment]
Closing this since we have already updated to `0.9.0`.

**Pull request closed without merging**
