### PR TITLE
Add and use prometheus-operator-crds component

### LINKED ISSUE #557: Allow installing prometheus-operator CRDs before prometheus-operator itself
To avoid chicken-egg issues with storage provider and prometheus-operator deployment like described in #433, we should have a way to install prometheus-operator CRDs before other components, so they can enable their monitoring from the very beginning. We could then even enable the monitoring by default and it would be left unused until user installs `prometheus-operator` component.

One "dummy" way would be to put the CRDs in separate component and then just inform users about correct ordering while configuring the cluster. More flexible way would be to dynamically pull this component as a dependency, when monitoring is enabled by other components.

### PR DESCRIPTION
**Pull request by invidian**
This PR adds new `prometheus-operator-crds`, which only ships prometheus-operator CRDs **and** a dummy object to workaround Helm bug https://github.com/helm/helm/issues/4670.

This new component is then added as a dependency of `prometheus-operator` component, from which the CRDs are removed.

This allows to install components in following order, which was not possible before:
1. Install prometheus-operator CRDs
2. Install storage provider **with monitoring enabled**
3. Install prometheus-operator itself

Closes #557

### CODE REVIEW

**Comment by surajssd** [comment]
I know prometheus operator is not part of control plane, but I think these CRDs should be part of the configs that bootkube installs.

Just like PodSecurityPolicy and NetworkPolicy which enhance the security of the system and are installed by default, monitoring in place by default increases the visibility into the system (much needed for complex behemoth like Kubernetes). Hence I argue that it should be part of default installation alongwith control plane configs.

### Pros:

- Enable Calico monitoring.
- The default(and the only) way to monitor the Lokomotive cluster is via prometheus operator and hence it should part of default installation just like Calico.
- This PR makes it user's concern to enable monitoring but IMHO user does not have to care about this at all. Monitoring configs(regarding components) will be installed by default once we enable this functionality.

### Cons:

- If user chooses to install prometheus-operator on their own, helm might complain about certain objects already exists because CRDs were installed already as a part of control plane.

**Comment by invidian** [comment]
>Just like PodSecurityPolicy and NetworkPolicy which enhance the security of the system and are installed by default, monitoring in place by default increases the visibility into the system (much needed for complex behemoth like Kubernetes). Hence I argue that it should be part of default installation alongwith control plane configs.

The difference though is, that PodSecurityPolicy and NetworkPolicy are native resources, consumed by Kubernetes itself. ServiceMonitor is fully 3rd party resource. As a user, if I don't plan to install monitoring, I'd also expect to not find the CRDs installed.

>This PR makes it user's concern to enable monitoring but IMHO user does not have to care about this at all. Monitoring configs(regarding components) will be installed by default once we enable this functionality.

This is user's concern for now, as we don't have a mechanism for dependencies and configuration enhancement. In the future, that detail will be hidden from the user.

**Comment by invidian** [comment]
Ping @surajssd @ipochi @johananl

**Comment by surajssd** [comment]
I don't like the UX of this. Just because some other component needs monitoring we force the user to add this one more component. IMO this should be automatic in some way for the user. We should always install this component unless user disables it.

**Comment by invidian** [comment]
I agree with you @surajssd, however, developing ideal solution will definitely take more time and this is very simple and just works :tm:

**Comment by johananl** [comment]
> I agree with you @surajssd, however, developing ideal solution will definitely take more time and this is very simple and just works

In deciding whether to merge this as is or develop a better solution, I think the question is - would the current UX improve or worsen if we merge this?

I agree with @surajssd that we shouldn't offload implementation problems onto the user. OTOH if something is currently broken and this PR makes it not broken, I'd say we should merge it until we have a better solution.

**Comment by surajssd** [comment]
Closing this PR in favour of https://github.com/kinvolk/lokomotive/pull/1351.

**Comment by invidian** [comment]
>In deciding whether to merge this as is or develop a better solution, I think the question is - would the current UX improve or worsen if we merge this?

IMO it improves usability, and UX but in a different direction than one would anticipate, as it unblocks installing monitoring right away (user benefit) without creating a burden (developer benefit).

**Pull request closed without merging**
