### PR TITLE
httpbin covert to helm chart

### PR DESCRIPTION
**Pull request by knrt10**
closes: #957

Signed-off-by: knrt10 <kautilya@kinvolk.io>

### CODE REVIEW

**Review by invidian — COMMENTED** [review]
LGTM except the CI failing.

**Comment by knrt10** [comment]
I don't know why it's failing, I ran `make update-assets`. still it fails

**Comment by invidian** [comment]
>I don't know why it's failing, I ran make update-assets. still it fails

you need to remove empty directory from assets, as `update-assets` includes it locally, but when you take your branch and do a fresh clone, git won't include empty directories.

**Comment by knrt10** [comment]
Thanks, didn't knew about this

**Comment by invidian** [comment]
>Thanks, didn't knew about this

Hmm, I guess we could run `find assets/ -type d -empty | wc -l` or something as part of the `update-assets` and fail if there are empty directories laying around there.

**Review by surajssd — APPROVED** [review]
code looks good to me

**Review by invidian — APPROVED** [review]

**Pull request merged**
