### PR TITLE
Update LICENSE copyright year to 2021

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Review by knrt10 — APPROVED** [review]

**Comment by invidian** [comment]
I wonder how does this work license-wise. Do those files need to have a year updated? Or maybe it must only be updated when the file is changed in a given year?

**Comment by surajssd** [comment]
@invidian I don't know :-| What do you suggest?

**Comment by iaguis** [comment]
I don't think we should update them every year. What I've seen elsewhere is that you update it if you make changes to a particular file because that's when you add new copyrighted code.

In any case you should keep the original year, because that's when at least part of the copyrighted code was written. So something like:

```
// Copyright 2020-2021 The Lokomotive Authors
```

**Comment by invidian** [comment]
How Kubernetes handles it for example?

**Pull request closed without merging**
