### PR TITLE
Remove not needed files from assets/lokomotive-kubernetes

### PR DESCRIPTION
**Pull request by invidian**
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

Perhaps we can take a look and move docs, which are worth keeping to `docs` directory.

### CODE REVIEW

**Comment by iaguis** [comment]
Kicked the CI again.

**Comment by invidian** [comment]
>LGTM, should we keep the licences around?

Good question. I was actually thinking if we should have copyright annotations in Terraform code in general.

From Typhoon perspective, Typhoon is MIT, so I think it's fine to remove those files.

**Comment by iaguis** [comment]
I think we need to keep the license files.

**Comment by invidian** [comment]
>I think we need to keep the license files.


All of them? So:
```
--- a/assets/lokomotive-kubernetes/LICENSE
--- a/assets/lokomotive-kubernetes/aws/flatcar-linux/kubernetes/LICENSE
--- a/assets/lokomotive-kubernetes/azure/flatcar-linux/kubernetes/LICENSE
--- a/assets/lokomotive-kubernetes/bare-metal/flatcar-linux/kubernetes/LICENSE
--- a/assets/lokomotive-kubernetes/bootkube/LICENSE
--- a/assets/lokomotive-kubernetes/google-cloud/flatcar-linux/kubernetes/LICENSE
```

**Comment by iaguis** [comment]
Yes

**Comment by invidian** [comment]
I restored LICENSE files then @iaguis.

**Pull request merged**
