### PR TITLE
Update cluster-autoscaler to version v1.1.0

### PR DESCRIPTION
**Pull request by knrt10**
Release info:
kubernetes/autoscaler/releases/tag/cluster-autoscaler-chart-1.1.0

Signed-off-by: knrt10 <kautilya@kinvolk.io>

### CODE REVIEW

**Review by invidian — COMMENTED** [review]
It seems something is not right, CI is failing.

**Comment by knrt10** [comment]
will fix it

**Comment by knrt10** [comment]
tested locally. Apart from CA not being reliable. Update was fine(updating component)

**Review by invidian — APPROVED** [review]
OK

**Review by surajssd — APPROVED** [review]

**Pull request merged**
