### PR TITLE
prometheus operator grafana: Generate password random, always

### PR DESCRIPTION
**Pull request by surajssd**
Fixes issue where grafana dashboard password is not random when user
does not provide the grafana block.

Fixes https://github.com/kinvolk/lokomotive/issues/506

---

TODOs:

- [x] Add test

### CODE REVIEW

**Comment by surajssd** [comment]
If you don't specify anything at all the values file from prometheus operator takes precedence:

https://github.com/kinvolk/lokomotive/blob/e849203966b90d61c8f9bdbf52f1413c193522ad/assets/components/prometheus-operator/manifests/values.yaml#L402

And it has default value of `prom-operator`.

But when you put an empty block following is set to empty string since field `AdminPassword` is string:

https://github.com/kinvolk/lokomotive/blob/e849203966b90d61c8f9bdbf52f1413c193522ad/pkg/components/prometheus-operator/template.go#L60

The lokoctl values file takes precedence even though it has empty string. And hence when you provide nothing or empty string to the chart itself it creates the random string:

https://github.com/kinvolk/lokomotive/blob/e849203966b90d61c8f9bdbf52f1413c193522ad/assets/components/prometheus-operator/manifests/charts/grafana/templates/secret.yaml#L13-L19

**Comment by surajssd** [comment]
> I think making a filed non-pointer make more sense in this case.

What is wrong with the current fix?

**Comment by surajssd** [comment]
@invidian I made following changes as you have mentioned:

```diff
diff --git a/pkg/components/prometheus-operator/component.go b/pkg/components/prometheus-operator/component.go
index ec266504..93b72b5e 100644
--- a/pkg/components/prometheus-operator/component.go
+++ b/pkg/components/prometheus-operator/component.go
@@ -53,7 +53,7 @@ type Grafana struct {
 }
 
 type component struct {
-	Grafana *Grafana `hcl:"grafana,block"`
+	Grafana Grafana `hcl:"grafana,block"`
 
 	Namespace string `hcl:"namespace,optional"`
 
@@ -122,7 +122,6 @@ func newComponent() *component {
 				"tier":    "control-plane",
 			},
 		},
-		Grafana: &Grafana{},
 	}
 }
 
@@ -137,7 +136,7 @@ func (c *component) LoadConfig(configBody *hcl.Body, evalContext *hcl.EvalContex
 		return err
 	}
 
-	if c.Grafana != nil && c.Grafana.Ingress != nil {
+	if c.Grafana.Ingress != nil {
 		c.Grafana.Ingress.SetDefaults()
 	}
```

And with following prometheus-operator config:

```tf
component "prometheus-operator" {}
```

But the insallation fails with following error:

```console
$ lokoctl component apply prometheus-operator
Applying component 'prometheus-operator'...
packet-cluster.lokocfg:77,33-33: Missing grafana block; A grafana block is required.
FATA[0000] packet-cluster.lokocfg:77,33-33: Missing grafana block; A grafana block is required.  args="[prometheus-operator]" command="lokoctl component apply"
```

How to make the block optional with hcl?

**Comment by invidian** [comment]
>How to make the block optional with hcl?

Ugh, I guess making it a pointer is the only way :neutral_face:

**Comment by invidian** [comment]
In this case, I still personally prefer the template solution over ensuring that the field is populated. One argument for that is, this does not block us from distinguishing, if user defined the empty `grafana` block in the future, in case we need that.

But so long there is a comment, why is it there, I'm fine with that.

**Comment by surajssd** [comment]
> LGTM. Thanks @surajssd and sorry for the noise around this PR.

It's alright :-) We have been only trying various options that are better from the perspective of maintainability. 

Thank you for the reviews.

**Pull request merged**
