### PR TITLE
Bump K8s version to 1.17.4

### PR DESCRIPTION
**Pull request by invidian**
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

### CODE REVIEW

**Comment by invidian** [comment]
>Please change the README.md to the new version too.

Should we remove patch version of K8s shipped from README.md maybe? I think which major and minor version we ship is a feature, but patch version is just a maintenance task.

**Comment by iaguis** [comment]
> Should we remove patch version of K8s shipped from README.md maybe? I think which major and minor version we ship is a feature, but patch version is just a maintenance task.

Sounds reasonable.

**Comment by invidian** [comment]
I also updated Go dependencies. I think that should be part of the upgrade process too.

**Comment by invidian** [comment]
>lgtm

Will wait for CI to pass before merging.

**Comment by iaguis** [comment]
> Will wait for CI to pass before merging.

as always :)

**Pull request merged**
