### PR TITLE
prometheus e2e: Parallelize the test runs

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by invidian** [comment]
I think this require retry loop, which is introduced in #208.

**Comment by surajssd** [comment]
About adding the retry logic here, what I am not really sure is

- if it is failing on the port forward setup ?
OR
- port forward passes and then when a call is made using it?

**Comment by invidian** [comment]
Good question. I _think_ port-forward is passing, but then it breaks. Perhaps as part of setting port forwarding, we should send some kind of ping to the server to make sure it's fine? I wonder if prometheus pod shows some restarts.

**Comment by invidian** [comment]
I'll test it on AKS to see if I can reproduce: https://yard.lokomotive-k8s.net/teams/main/pipelines/lokomotive-oss-aks-testing-mateusz/jobs/test-lokomotive-aks-deployment/builds/5.

**Comment by surajssd** [comment]
> Good question. I think port-forward is passing, but then it breaks. Perhaps as part of setting port forwarding, we should send some kind of ping to the server to make sure it's fine? I wonder if prometheus pod shows some restarts.

Yeah possible that the port has restarted, but then there is no way to know it for real. Maybe dumping full fledged information of the cluster at the end of test fail can help us do some investigation and draw some hypothesis based on that.

**Comment by invidian** [comment]
```diff
diff --git a/test/monitoring/monitoring_test.go b/test/monitoring/monitoring_test.go
index 4ca5d61d..985a220e 100644
--- a/test/monitoring/monitoring_test.go
+++ b/test/monitoring/monitoring_test.go
@@ -28,6 +28,8 @@ import (
 )
 
 func TestPrometheus(t *testing.T) {
+       t.Parallel()
+
        const prometheusPodPort = 9090
 
        p := &testutil.PortForwardInfo{
@@ -68,11 +70,18 @@ func TestPrometheus(t *testing.T) {
                },
        }
 
-       // Invoke the test functions passing them the test object and the prometheus client.
-       for _, test := range tests {
-               test := test
-               t.Run(test.Name, func(t *testing.T) {
-                       test.Func(t, v1api)
-               })
-       }
+       // We need to wrap with t.Run() twice, so defer does not close port forwarding before
+       // all subtests are finished.
+       // See https://github.com/golang/go/issues/17791#issuecomment-259976524 for details.
+       t.Run("wait_group", func(t *testing.T) {
+               // Invoke the test functions passing them the test object and the prometheus client.
+               for _, test := range tests {
+                       test := test
+                       t.Run(test.Name, func(t *testing.T) {
+                               t.Parallel()
+
+                               test.Func(t, v1api)
+                       })
+               }
+       })
 }
```

This works for me.

**Comment by surajssd** [comment]
Since all the sub tests are running in parallel anyway we don't need to do this again.

**Pull request closed without merging**
