### PR TITLE
Update linkerd to 2.10.2

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by surajssd** [comment]
Something is wrong with the AWS installation, that it does not wait until all the LinkerD pods are up. Meanwhile in Packet it does wait.

**Comment by ipochi** [comment]
> Something is wrong with the AWS installation, that it does not wait until all the LinkerD pods are up. Meanwhile in Packet it does wait.

Is this resolved. Might we add a note that on AWS this is expected and known ?

**Review by ipochi — APPROVED** [review]
I haven't test myself but LGTM on the outside with one comment/suggestion.

**Comment by surajssd** [comment]
> Something is wrong with the AWS installation, that it does not wait until all the LinkerD pods are up. Meanwhile in Packet it does wait.

Yes it was resolved by making the Linkerd control plane HA.

**Pull request merged**
