### PR TITLE
readme: Add example gif

### PR DESCRIPTION
**Pull request by BrainBlasted**
Related to https://github.com/kinvolk/lokomotive/issues/318

### CODE REVIEW

**Comment by knrt10** [comment]
@BrainBlasted is it possible for the video to be fast, I mean show the main working, skipping the 5-6 minute idle gap.

**Comment by iaguis** [comment]
> @BrainBlasted is it possible for the video to be fast, I mean show the main working, skipping the 5-6 minute idle gap.

Is this something you can do, @BrainBlasted?

**Comment by BrainBlasted** [comment]
Yes, though I need to figure out the right tools for gif editing, as my video editors can't seem to handle them.On Jun 25, 2020 9:08 AM, Iago López Galeiras <notifications@github.com> wrote:

@BrainBlasted is it possible for the video to be fast, I mean show the main working, skipping the 5-6 minute idle gap.

Is this something you can do, @BrainBlasted?

**Comment by BrainBlasted** [comment]
Pushed a new version with an edited gif.

**Comment by BrainBlasted** [comment]
Made requested changes :)

**Comment by iaguis** [comment]
I think there's still a pretty big gap (40s), I edited the gif a bit so it's more engaging, maybe you can use it. What do you think?

lokomotive-example2

**Comment by BrainBlasted** [comment]
I think this looks good :) Will incorporate it.

**Comment by BrainBlasted** [comment]
I think this is ready now.

**Pull request merged**
