### PR TITLE
kubelet dashboard: Remove the cluster label

### PR DESCRIPTION
**Pull request by surajssd**
Kubelet Dashboard was not showing any information because it was
querying using the cluster label which was missing on the metrics. This
commit removes the cluster label query.

Fixes https://github.com/kinvolk/lokomotive/issues/453

### CODE REVIEW

**Comment by surajssd** [comment]
The dashboard looks like this with this PR:

Screenshot from 2020-05-22 18-40-56

**Comment by surajssd** [comment]
But then do we have an option until we update the chart to the latest version?

**Comment by invidian** [comment]
Hm, could we just update to the latest version with https://github.com/helm/charts/pull/22338 included on top? As I guess this is the issue? Instead of this PR.

**Comment by surajssd** [comment]
I am not sure how that PR can be implemented. Because it is supposed to maintain two appVersions, not sure how that can be achieved.

**Comment by invidian** [comment]
>I am not sure how that PR can be implemented. Because it is supposed to maintain two appVersions, not sure how that can be achieved.

Maybe you can fallback to value different than appVersion if K8s version is lower than X?

**Comment by iaguis** [comment]
I don't have all the context but it seems https://github.com/helm/charts/pull/22338 is closed so are you ok with having this as a stop-gap solution and consider updating to a newer chart once it's available upstream, @invidian?

**Comment by invidian** [comment]
>I don't have all the context but it seems helm/charts#22338 is closed so are you ok with having this as a stop-gap solution and consider updating to a newer chart once it's available upstream, @invidian?

As far as I understand, we ship dashboards, which is suppose to be used with Kubernetes 1.14, when Lokomotive ships 1.18. There might be other things broken in those dashboards because of that, not only this. We might be also missing some interesting graphs etc.

For me, maintaining/fixing the dashboards which shouldn't be used anyway and should be replaced makes a little sense, I would rather move forward and catch up with upstream. Also, as far as I see, upstream is not willing to do the upgrades, as the repository is deprecated.

**Comment by iaguis** [comment]
> As far as I understand, we ship dashboards, which is suppose to be used with Kubernetes 1.14, when Lokomotive ships 1.18. There might be other things broken in those dashboards because of that, not only this. We might be also missing some interesting graphs etc.
> 
> For me, maintaining/fixing the dashboards which shouldn't be used anyway and should be replaced makes a little sense, I would rather move forward and catch up with upstream. Also, as far as I see, upstream is not willing to do the upgrades, as the repository is deprecated.

I agree with the general idea. However, things are broken right now so I'd say:

* If we need this fixed right away, and since updating to current dashboards seems like a fair amount of work, let's fix the issues we found and keep using 1.14 dashboards and create an issue to update to the latest Prometheus-operator/dashboards.
* If we don't need it right away let's invest in updating Prometheus-operator in this PR.

**Comment by surajssd** [comment]
> If we don't need it right away let's invest in updating Prometheus-operator in this PR.

It is a huge effort since upstream for the sake for backwards compatibility does not want to make much changes as mentioned in that closed PR.

I suggest we move forward with this because things work fine for now. And we revisit things as they are broken.

**Comment by surajssd** [comment]
@invidian @iaguis PTAL

**Pull request merged**
